"C:\Program Files (x86)\JetBrains\PyCharm 2016.1.4\bin\runnerw.exe" C:\Python27\python.exe C:/Users/diego/OneDrive/Projetos/sistema_contabil/manage.py runserver localhost:8000
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2016 - 02:07:15
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
[18/Nov/2016 02:07:16] "GET / HTTP/1.1" 200 14491
[18/Nov/2016 02:23:10] "GET / HTTP/1.1" 200 14491
[18/Nov/2016 02:39:02] "GET / HTTP/1.1" 200 14491
[18/Nov/2016 02:47:24] "GET / HTTP/1.1" 200 14491
[18/Nov/2016 03:04:44] "GET / HTTP/1.1" 200 14491
[18/Nov/2016 03:25:51] "GET / HTTP/1.1" 200 14491
[18/Nov/2016 03:48:12] "GET / HTTP/1.1" 200 14491
[18/Nov/2016 04:11:43] "GET / HTTP/1.1" 200 14491
[18/Nov/2016 04:35:18] "GET / HTTP/1.1" 200 14491
[18/Nov/2016 04:49:56] "GET / HTTP/1.1" 200 14491
[18/Nov/2016 05:02:09] "GET / HTTP/1.1" 200 14491
[18/Nov/2016 05:31:01] "GET / HTTP/1.1" 200 14491
[18/Nov/2016 05:37:16] "GET / HTTP/1.1" 200 14491
[18/Nov/2016 05:37:16] "GET /arquivos_estaticos/icones/fonts/fontawesome-webfont.woff2?v=4.3.0 HTTP/1.1" 200 56780
[18/Nov/2016 05:37:40] "GET /entidade/cadastro/ HTTP/1.1" 200 33447
[18/Nov/2016 05:37:40] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 05:37:40] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:37:40] "GET /arquivos_estaticos/bootstrap/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 18028
[18/Nov/2016 05:37:40] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:37:40] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 05:39:51] "GET /entidade/cadastro/ HTTP/1.1" 200 33458
[18/Nov/2016 05:39:51] "GET /arquivos_estaticos/adminlte/css/AdminLTE.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:39:51] "GET /arquivos_estaticos/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:39:51] "GET /arquivos_estaticos/icones/css/font-awesome.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:39:51] "GET /arquivos_estaticos/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:39:51] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.js HTTP/1.1" 304 0
[18/Nov/2016 05:39:51] "GET /arquivos_estaticos/jquery/jquery-2.2.0.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:39:52] "GET /arquivos_estaticos/adminlte/css/skins/skin-blue.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:39:52] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.css HTTP/1.1" 304 0
[18/Nov/2016 05:39:52] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/css/dataTables.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:39:52] "GET /arquivos_estaticos/datatable/plugins/responsivo/Responsive-2.0.2/css/responsive.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:39:52] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/css/select.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:39:52] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/jquery.dataTables.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:39:53] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/dataTables.bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:39:53] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/js/dataTables.select.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:39:53] "GET /arquivos_estaticos/adminlte/js/app.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:39:53] "GET /arquivos_estaticos/scripts/padrao/controle_componentes.js HTTP/1.1" 304 0
[18/Nov/2016 05:39:53] "GET /arquivos_estaticos/scripts/mask.js HTTP/1.1" 304 0
[18/Nov/2016 05:39:53] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:39:53] "GET /arquivos_estaticos/imagens/logo.png HTTP/1.1" 304 0
[18/Nov/2016 05:39:53] "GET /arquivos_estaticos/imagens/avatar5.png HTTP/1.1" 304 0
[18/Nov/2016 05:39:53] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 05:39:53] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:39:53] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 05:40:16] "GET /entidade/cadastro/ HTTP/1.1" 200 33485
[18/Nov/2016 05:40:16] "GET /arquivos_estaticos/adminlte/css/AdminLTE.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:40:16] "GET /arquivos_estaticos/icones/css/font-awesome.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:40:16] "GET /arquivos_estaticos/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:40:16] "GET /arquivos_estaticos/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:40:16] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.js HTTP/1.1" 304 0
[18/Nov/2016 05:40:16] "GET /arquivos_estaticos/jquery/jquery-2.2.0.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:40:17] "GET /arquivos_estaticos/adminlte/css/skins/skin-blue.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:40:17] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.css HTTP/1.1" 304 0
[18/Nov/2016 05:40:17] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/css/dataTables.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:40:17] "GET /arquivos_estaticos/datatable/plugins/responsivo/Responsive-2.0.2/css/responsive.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:40:17] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/css/select.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:40:17] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/jquery.dataTables.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:40:17] "GET /arquivos_estaticos/scripts/padrao/controle_componentes.js HTTP/1.1" 304 0
[18/Nov/2016 05:40:17] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/js/dataTables.select.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:40:17] "GET /arquivos_estaticos/adminlte/js/app.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:40:17] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/dataTables.bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:40:17] "GET /arquivos_estaticos/scripts/mask.js HTTP/1.1" 304 0
[18/Nov/2016 05:40:17] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:40:18] "GET /arquivos_estaticos/imagens/avatar5.png HTTP/1.1" 304 0
[18/Nov/2016 05:40:18] "GET /arquivos_estaticos/imagens/logo.png HTTP/1.1" 304 0
[18/Nov/2016 05:40:18] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 05:40:18] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:40:18] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 05:40:39] "GET /entidade/cadastro/ HTTP/1.1" 200 33513
[18/Nov/2016 05:40:39] "GET /arquivos_estaticos/adminlte/css/AdminLTE.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:40:39] "GET /arquivos_estaticos/icones/css/font-awesome.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:40:39] "GET /arquivos_estaticos/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:40:39] "GET /arquivos_estaticos/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:40:39] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.js HTTP/1.1" 304 0
[18/Nov/2016 05:40:39] "GET /arquivos_estaticos/jquery/jquery-2.2.0.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:40:40] "GET /arquivos_estaticos/adminlte/css/skins/skin-blue.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:40:40] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.css HTTP/1.1" 304 0
[18/Nov/2016 05:40:40] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/css/dataTables.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:40:40] "GET /arquivos_estaticos/datatable/plugins/responsivo/Responsive-2.0.2/css/responsive.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:40:40] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/css/select.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:40:40] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/jquery.dataTables.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:40:41] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/dataTables.bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:40:41] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/js/dataTables.select.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:40:41] "GET /arquivos_estaticos/adminlte/js/app.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:40:41] "GET /arquivos_estaticos/scripts/padrao/controle_componentes.js HTTP/1.1" 304 0
[18/Nov/2016 05:40:41] "GET /arquivos_estaticos/scripts/mask.js HTTP/1.1" 304 0
[18/Nov/2016 05:40:41] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:40:41] "GET /arquivos_estaticos/imagens/avatar5.png HTTP/1.1" 304 0
[18/Nov/2016 05:40:41] "GET /arquivos_estaticos/imagens/logo.png HTTP/1.1" 304 0
[18/Nov/2016 05:40:41] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 05:40:41] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:40:41] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 05:41:02] "GET /entidade/cadastro/ HTTP/1.1" 200 33512
[18/Nov/2016 05:41:02] "GET /arquivos_estaticos/adminlte/css/AdminLTE.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:41:02] "GET /arquivos_estaticos/icones/css/font-awesome.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:41:02] "GET /arquivos_estaticos/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:41:02] "GET /arquivos_estaticos/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:41:02] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.js HTTP/1.1" 304 0
[18/Nov/2016 05:41:02] "GET /arquivos_estaticos/jquery/jquery-2.2.0.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:41:03] "GET /arquivos_estaticos/adminlte/css/skins/skin-blue.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:41:03] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.css HTTP/1.1" 304 0
[18/Nov/2016 05:41:03] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/css/dataTables.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:41:03] "GET /arquivos_estaticos/datatable/plugins/responsivo/Responsive-2.0.2/css/responsive.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:41:03] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/css/select.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:41:03] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/jquery.dataTables.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:41:03] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/dataTables.bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:41:03] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/js/dataTables.select.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:41:03] "GET /arquivos_estaticos/adminlte/js/app.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:41:03] "GET /arquivos_estaticos/scripts/padrao/controle_componentes.js HTTP/1.1" 304 0
[18/Nov/2016 05:41:03] "GET /arquivos_estaticos/scripts/mask.js HTTP/1.1" 304 0
[18/Nov/2016 05:41:03] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:41:04] "GET /arquivos_estaticos/imagens/avatar5.png HTTP/1.1" 304 0
[18/Nov/2016 05:41:04] "GET /arquivos_estaticos/imagens/logo.png HTTP/1.1" 304 0
[18/Nov/2016 05:41:04] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 05:41:04] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:41:04] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 05:41:28] "GET /entidade/cadastro/ HTTP/1.1" 200 33513
[18/Nov/2016 05:41:28] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.js HTTP/1.1" 304 0
[18/Nov/2016 05:41:28] "GET /arquivos_estaticos/jquery/jquery-2.2.0.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:41:28] "GET /arquivos_estaticos/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:41:28] "GET /arquivos_estaticos/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:41:28] "GET /arquivos_estaticos/adminlte/css/AdminLTE.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:41:28] "GET /arquivos_estaticos/icones/css/font-awesome.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:41:28] "GET /arquivos_estaticos/adminlte/css/skins/skin-blue.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:41:28] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.css HTTP/1.1" 304 0
[18/Nov/2016 05:41:28] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/css/dataTables.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:41:28] "GET /arquivos_estaticos/datatable/plugins/responsivo/Responsive-2.0.2/css/responsive.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:41:28] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/css/select.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:41:28] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/jquery.dataTables.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:41:28] "GET /arquivos_estaticos/adminlte/js/app.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:41:28] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/js/dataTables.select.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:41:28] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/dataTables.bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:41:28] "GET /arquivos_estaticos/scripts/padrao/controle_componentes.js HTTP/1.1" 304 0
[18/Nov/2016 05:41:28] "GET /arquivos_estaticos/scripts/mask.js HTTP/1.1" 304 0
[18/Nov/2016 05:41:28] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:41:28] "GET /arquivos_estaticos/imagens/avatar5.png HTTP/1.1" 304 0
[18/Nov/2016 05:41:28] "GET /arquivos_estaticos/imagens/logo.png HTTP/1.1" 304 0
[18/Nov/2016 05:41:28] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 05:41:28] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:41:29] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 05:44:01] "GET /entidade/cadastro/ HTTP/1.1" 200 33537
[18/Nov/2016 05:44:02] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:44:02] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 05:44:02] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
problema no formulario
<ul class="errorlist"><li>tabela<ul class="errorlist"><li>Certifique-se de que o valor tenha no máximo 6 caracteres (ele possui 8).</li></ul></li></ul>
[18/Nov/2016 05:48:13] "POST /entidade/cadastro/ HTTP/1.1" 200 34108
[18/Nov/2016 05:48:14] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:48:14] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 05:48:14] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2016 - 05:48:44
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
erros:  tabela
problema no formulario
<ul class="errorlist"><li>tabela<ul class="errorlist"><li>Certifique-se de que o valor tenha no máximo 6 caracteres (ele possui 8).</li></ul></li></ul>
[18/Nov/2016 05:48:51] "POST /entidade/cadastro/ HTTP/1.1" 200 34108
[18/Nov/2016 05:48:51] "GET /arquivos_estaticos/adminlte/css/AdminLTE.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:48:51] "GET /arquivos_estaticos/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:48:51] "GET /arquivos_estaticos/icones/css/font-awesome.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:48:51] "GET /arquivos_estaticos/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:48:51] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.js HTTP/1.1" 304 0
[18/Nov/2016 05:48:51] "GET /arquivos_estaticos/jquery/jquery-2.2.0.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:48:52] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.css HTTP/1.1" 304 0
[18/Nov/2016 05:48:52] "GET /arquivos_estaticos/adminlte/css/skins/skin-blue.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:48:52] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/css/dataTables.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:48:52] "GET /arquivos_estaticos/datatable/plugins/responsivo/Responsive-2.0.2/css/responsive.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:48:52] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/css/select.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:48:52] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/jquery.dataTables.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:48:52] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/dataTables.bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:48:52] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/js/dataTables.select.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:48:52] "GET /arquivos_estaticos/adminlte/js/app.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:48:52] "GET /arquivos_estaticos/scripts/padrao/controle_componentes.js HTTP/1.1" 304 0
[18/Nov/2016 05:48:52] "GET /arquivos_estaticos/scripts/mask.js HTTP/1.1" 304 0
[18/Nov/2016 05:48:52] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:48:53] "GET /arquivos_estaticos/imagens/avatar5.png HTTP/1.1" 304 0
[18/Nov/2016 05:48:53] "GET /arquivos_estaticos/imagens/logo.png HTTP/1.1" 304 0
[18/Nov/2016 05:48:53] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 05:48:53] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:48:53] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2016 - 05:49:31
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
Formulario ok
[18/Nov/2016 05:49:32] "POST /entidade/cadastro/ HTTP/1.1" 200 33936
[18/Nov/2016 05:49:32] "GET /arquivos_estaticos/jquery/jquery-2.2.0.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:49:32] "GET /arquivos_estaticos/adminlte/css/AdminLTE.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:49:32] "GET /arquivos_estaticos/icones/css/font-awesome.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:49:32] "GET /arquivos_estaticos/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:49:32] "GET /arquivos_estaticos/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:49:32] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.js HTTP/1.1" 304 0
[18/Nov/2016 05:49:33] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.css HTTP/1.1" 304 0
[18/Nov/2016 05:49:33] "GET /arquivos_estaticos/adminlte/css/skins/skin-blue.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:49:33] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/css/dataTables.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:49:33] "GET /arquivos_estaticos/datatable/plugins/responsivo/Responsive-2.0.2/css/responsive.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:49:33] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/css/select.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:49:33] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/jquery.dataTables.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:49:33] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/dataTables.bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:49:33] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/js/dataTables.select.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:49:33] "GET /arquivos_estaticos/adminlte/js/app.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:49:33] "GET /arquivos_estaticos/scripts/padrao/controle_componentes.js HTTP/1.1" 304 0
[18/Nov/2016 05:49:33] "GET /arquivos_estaticos/scripts/mask.js HTTP/1.1" 304 0
[18/Nov/2016 05:49:33] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:49:33] "GET /arquivos_estaticos/imagens/avatar5.png HTTP/1.1" 304 0
[18/Nov/2016 05:49:33] "GET /arquivos_estaticos/imagens/logo.png HTTP/1.1" 304 0
[18/Nov/2016 05:49:33] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 05:49:33] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:49:34] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2016 - 05:50:15
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
[18/Nov/2016 05:51:20] "GET /entidade/cadastro/ HTTP/1.1" 200 33538
[18/Nov/2016 05:51:21] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 05:51:21] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:51:21] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
erros: Internal Server Error: /entidade/cadastro/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 73, in cadastro_entidades
    print "erros: ",item.text
AttributeError: 'str' object has no attribute 'text'
Internal Server Error: /entidade/cadastro/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 73, in cadastro_entidades
    print "erros: ",item.text
AttributeError: 'str' object has no attribute 'text'
[18/Nov/2016 05:51:25] "POST /entidade/cadastro/ HTTP/1.1" 500 65664

Performing system checks...

System check identified no issues (0 silenced).
November 18, 2016 - 05:51:40
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
erros:  justificativa
problema no formulario
<ul class="errorlist"><li>justificativa<ul class="errorlist"><li>Precisa ser Informado!</li></ul></li></ul>
[18/Nov/2016 05:51:41] "POST /entidade/cadastro/ HTTP/1.1" 200 34060
[18/Nov/2016 05:51:41] "GET /arquivos_estaticos/icones/css/font-awesome.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:51:41] "GET /arquivos_estaticos/adminlte/css/AdminLTE.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:51:41] "GET /arquivos_estaticos/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:51:41] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.js HTTP/1.1" 304 0
[18/Nov/2016 05:51:41] "GET /arquivos_estaticos/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:51:41] "GET /arquivos_estaticos/jquery/jquery-2.2.0.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:51:42] "GET /arquivos_estaticos/adminlte/css/skins/skin-blue.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:51:42] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/css/dataTables.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:51:42] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.css HTTP/1.1" 304 0
[18/Nov/2016 05:51:42] "GET /arquivos_estaticos/datatable/plugins/responsivo/Responsive-2.0.2/css/responsive.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:51:42] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/css/select.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:51:42] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/jquery.dataTables.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:51:43] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/js/dataTables.select.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:51:43] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/dataTables.bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:51:43] "GET /arquivos_estaticos/adminlte/js/app.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:51:43] "GET /arquivos_estaticos/scripts/padrao/controle_componentes.js HTTP/1.1" 304 0
[18/Nov/2016 05:51:43] "GET /arquivos_estaticos/scripts/mask.js HTTP/1.1" 304 0
[18/Nov/2016 05:51:43] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:51:43] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 05:51:43] "GET /arquivos_estaticos/imagens/avatar5.png HTTP/1.1" 304 0
[18/Nov/2016 05:51:43] "GET /arquivos_estaticos/imagens/logo.png HTTP/1.1" 304 0
[18/Nov/2016 05:51:43] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:51:44] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2016 - 05:56:14
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
Internal Server Error: /entidade/cadastro/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 72, in cadastro_entidades
    msg = verificar_erro(formulario)
NameError: global name 'formulario' is not defined
Internal Server Error: /entidade/cadastro/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 72, in cadastro_entidades
    msg = verificar_erro(formulario)
NameError: global name 'formulario' is not defined
[18/Nov/2016 05:56:15] "POST /entidade/cadastro/ HTTP/1.1" 500 65629
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2016 - 05:56:25
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
erros:  Justificativa: Precisa ser Informado!
problema no formulario
<ul class="errorlist"><li>justificativa<ul class="errorlist"><li>Precisa ser Informado!</li></ul></li></ul>
[18/Nov/2016 05:56:27] "POST /entidade/cadastro/ HTTP/1.1" 200 34060
[18/Nov/2016 05:56:27] "GET /arquivos_estaticos/adminlte/css/AdminLTE.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:56:27] "GET /arquivos_estaticos/icones/css/font-awesome.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:56:27] "GET /arquivos_estaticos/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:56:27] "GET /arquivos_estaticos/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:56:27] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.js HTTP/1.1" 304 0
[18/Nov/2016 05:56:27] "GET /arquivos_estaticos/jquery/jquery-2.2.0.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:56:27] "GET /arquivos_estaticos/adminlte/css/skins/skin-blue.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:56:27] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.css HTTP/1.1" 304 0
[18/Nov/2016 05:56:27] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/css/dataTables.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:56:27] "GET /arquivos_estaticos/datatable/plugins/responsivo/Responsive-2.0.2/css/responsive.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:56:27] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/css/select.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:56:27] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/jquery.dataTables.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:56:28] "GET /arquivos_estaticos/scripts/mask.js HTTP/1.1" 304 0
[18/Nov/2016 05:56:28] "GET /arquivos_estaticos/adminlte/js/app.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:56:28] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/js/dataTables.select.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:56:28] "GET /arquivos_estaticos/scripts/padrao/controle_componentes.js HTTP/1.1" 304 0
[18/Nov/2016 05:56:28] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/dataTables.bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:56:28] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:56:28] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 05:56:28] "GET /arquivos_estaticos/imagens/logo.png HTTP/1.1" 304 0
[18/Nov/2016 05:56:28] "GET /arquivos_estaticos/imagens/avatar5.png HTTP/1.1" 304 0
[18/Nov/2016 05:56:28] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:56:28] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2016 - 05:57:02
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
[18/Nov/2016 05:57:13] "POST /entidade/cadastro/ HTTP/1.1" 200 34063
[18/Nov/2016 05:57:13] "GET /arquivos_estaticos/adminlte/css/AdminLTE.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:57:13] "GET /arquivos_estaticos/icones/css/font-awesome.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:57:13] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.js HTTP/1.1" 304 0
[18/Nov/2016 05:57:13] "GET /arquivos_estaticos/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:57:13] "GET /arquivos_estaticos/jquery/jquery-2.2.0.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:57:13] "GET /arquivos_estaticos/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:57:13] "GET /arquivos_estaticos/adminlte/css/skins/skin-blue.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:57:13] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.css HTTP/1.1" 304 0
[18/Nov/2016 05:57:13] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/css/dataTables.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:57:13] "GET /arquivos_estaticos/datatable/plugins/responsivo/Responsive-2.0.2/css/responsive.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:57:13] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/css/select.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:57:13] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/jquery.dataTables.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:57:13] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/js/dataTables.select.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:57:13] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/dataTables.bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:57:13] "GET /arquivos_estaticos/adminlte/js/app.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:57:13] "GET /arquivos_estaticos/scripts/padrao/controle_componentes.js HTTP/1.1" 304 0
[18/Nov/2016 05:57:13] "GET /arquivos_estaticos/scripts/mask.js HTTP/1.1" 304 0
[18/Nov/2016 05:57:13] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:57:13] "GET /arquivos_estaticos/imagens/avatar5.png HTTP/1.1" 304 0
[18/Nov/2016 05:57:13] "GET /arquivos_estaticos/imagens/logo.png HTTP/1.1" 304 0
[18/Nov/2016 05:57:13] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 05:57:13] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:57:14] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2016 - 05:57:25
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
[18/Nov/2016 05:57:40] "POST /entidade/cadastro/ HTTP/1.1" 200 34057
[18/Nov/2016 05:57:40] "GET /arquivos_estaticos/adminlte/css/AdminLTE.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:57:40] "GET /arquivos_estaticos/icones/css/font-awesome.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:57:40] "GET /arquivos_estaticos/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:57:40] "GET /arquivos_estaticos/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:57:40] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.js HTTP/1.1" 304 0
[18/Nov/2016 05:57:40] "GET /arquivos_estaticos/jquery/jquery-2.2.0.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:57:40] "GET /arquivos_estaticos/adminlte/css/skins/skin-blue.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:57:40] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.css HTTP/1.1" 304 0
[18/Nov/2016 05:57:40] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/css/dataTables.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:57:40] "GET /arquivos_estaticos/datatable/plugins/responsivo/Responsive-2.0.2/css/responsive.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:57:40] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/css/select.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 05:57:40] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/jquery.dataTables.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:57:41] "GET /arquivos_estaticos/scripts/padrao/controle_componentes.js HTTP/1.1" 304 0
[18/Nov/2016 05:57:41] "GET /arquivos_estaticos/adminlte/js/app.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:57:41] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/js/dataTables.select.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:57:41] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/dataTables.bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 05:57:41] "GET /arquivos_estaticos/scripts/mask.js HTTP/1.1" 304 0
[18/Nov/2016 05:57:41] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:57:41] "GET /arquivos_estaticos/imagens/avatar5.png HTTP/1.1" 304 0
[18/Nov/2016 05:57:41] "GET /arquivos_estaticos/imagens/logo.png HTTP/1.1" 304 0
[18/Nov/2016 05:57:41] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 05:57:41] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 05:57:41] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2016 - 06:00:19
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
[18/Nov/2016 06:05:31] "GET /entidade/cadastro/ HTTP/1.1" 200 33538
[18/Nov/2016 06:05:32] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 06:05:32] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 06:05:32] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
Internal Server Error: /entidade/cadastro/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 70, in cadastro_entidades
    operacao_tabela = form_desativar['operacao_tabela'].value()
  File "C:\Python27\lib\site-packages\django\forms\forms.py", line 144, in __getitem__
    "Key %r not found in '%s'" % (name, self.__class__.__name__))
KeyError: u"Key 'operacao_tabela' not found in 'formulario_justificar_operacao'"
Internal Server Error: /entidade/cadastro/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 70, in cadastro_entidades
    operacao_tabela = form_desativar['operacao_tabela'].value()
  File "C:\Python27\lib\site-packages\django\forms\forms.py", line 144, in __getitem__
    "Key %r not found in '%s'" % (name, self.__class__.__name__))
KeyError: u"Key 'operacao_tabela' not found in 'formulario_justificar_operacao'"
[18/Nov/2016 06:05:41] "POST /entidade/cadastro/ HTTP/1.1" 500 69607
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2016 - 06:06:20
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
Internal Server Error: /entidade/cadastro/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 71, in cadastro_entidades
    operacao_user = form_desativar['operacao_user'].value()
  File "C:\Python27\lib\site-packages\django\forms\forms.py", line 144, in __getitem__
    "Key %r not found in '%s'" % (name, self.__class__.__name__))
KeyError: u"Key 'operacao_user' not found in 'formulario_justificar_operacao'"
Internal Server Error: /entidade/cadastro/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 71, in cadastro_entidades
    operacao_user = form_desativar['operacao_user'].value()
  File "C:\Python27\lib\site-packages\django\forms\forms.py", line 144, in __getitem__
    "Key %r not found in '%s'" % (name, self.__class__.__name__))
KeyError: u"Key 'operacao_user' not found in 'formulario_justificar_operacao'"
[18/Nov/2016 06:06:22] "POST /entidade/cadastro/ HTTP/1.1" 500 69899
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2016 - 06:06:48
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
Internal Server Error: /entidade/cadastro/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 80, in cadastro_entidades
    operacao.user = operacao_user
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 207, in __set__
    self.field.remote_field.model._meta.object_name,
ValueError: Cannot assign "u'1'": "OperacaoRestrita.user" must be a "User" instance.
Internal Server Error: /entidade/cadastro/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 80, in cadastro_entidades
    operacao.user = operacao_user
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 207, in __set__
    self.field.remote_field.model._meta.object_name,
ValueError: Cannot assign "u'1'": "OperacaoRestrita.user" must be a "User" instance.
[18/Nov/2016 06:06:49] "POST /entidade/cadastro/ HTTP/1.1" 500 71137
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2016 - 06:07:22
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
Internal Server Error: /entidade/cadastro/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 80, in cadastro_entidades
    operacao.user = operacao_user
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 207, in __set__
    self.field.remote_field.model._meta.object_name,
ValueError: Cannot assign "u'1'": "OperacaoRestrita.user" must be a "User" instance.
Internal Server Error: /entidade/cadastro/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 80, in cadastro_entidades
    operacao.user = operacao_user
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 207, in __set__
    self.field.remote_field.model._meta.object_name,
ValueError: Cannot assign "u'1'": "OperacaoRestrita.user" must be a "User" instance.
[18/Nov/2016 06:07:30] "POST /entidade/cadastro/ HTTP/1.1" 500 71125
Internal Server Error: /entidade/cadastro/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 80, in cadastro_entidades
    operacao.user = operacao_user
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 207, in __set__
    self.field.remote_field.model._meta.object_name,
ValueError: Cannot assign "u'1'": "OperacaoRestrita.user" must be a "User" instance.
Internal Server Error: /entidade/cadastro/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 80, in cadastro_entidades
    operacao.user = operacao_user
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 207, in __set__
    self.field.remote_field.model._meta.object_name,
ValueError: Cannot assign "u'1'": "OperacaoRestrita.user" must be a "User" instance.
[18/Nov/2016 06:07:39] "POST /entidade/cadastro/ HTTP/1.1" 500 71125
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2016 - 06:08:02
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
Internal Server Error: /entidade/cadastro/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 80, in cadastro_entidades
    operacao.user = None
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 199, in __set__
    (instance._meta.object_name, self.field.name)
ValueError: Cannot assign None: "OperacaoRestrita.user" does not allow null values.
Internal Server Error: /entidade/cadastro/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 80, in cadastro_entidades
    operacao.user = None
  File "C:\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 199, in __set__
    (instance._meta.object_name, self.field.name)
ValueError: Cannot assign None: "OperacaoRestrita.user" does not allow null values.
[18/Nov/2016 06:08:06] "POST /entidade/cadastro/ HTTP/1.1" 500 71070
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2016 - 06:08:44
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
Internal Server Error: /entidade/cadastro/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 91, in cadastro_entidades
    operacao.save()
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 659, in save
    "unsaved related object '%s'." % field.name
ValueError: save() prohibited to prevent data loss due to unsaved related object 'user'.
Internal Server Error: /entidade/cadastro/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 91, in cadastro_entidades
    operacao.save()
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 659, in save
    "unsaved related object '%s'." % field.name
ValueError: save() prohibited to prevent data loss due to unsaved related object 'user'.
[18/Nov/2016 06:09:02] "POST /entidade/cadastro/ HTTP/1.1" 500 71793
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2016 - 06:09:28
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2016 - 06:11:04
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
[18/Nov/2016 06:13:19] "POST /entidade/cadastro/ HTTP/1.1" 200 33936
[18/Nov/2016 06:13:19] "GET /arquivos_estaticos/adminlte/css/AdminLTE.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:13:19] "GET /arquivos_estaticos/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:13:19] "GET /arquivos_estaticos/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:13:19] "GET /arquivos_estaticos/icones/css/font-awesome.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:13:19] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.js HTTP/1.1" 304 0
[18/Nov/2016 06:13:19] "GET /arquivos_estaticos/jquery/jquery-2.2.0.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:13:20] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/css/dataTables.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:13:20] "GET /arquivos_estaticos/adminlte/css/skins/skin-blue.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:13:20] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.css HTTP/1.1" 304 0
[18/Nov/2016 06:13:20] "GET /arquivos_estaticos/datatable/plugins/responsivo/Responsive-2.0.2/css/responsive.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:13:20] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/css/select.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:13:20] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/jquery.dataTables.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:13:20] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/dataTables.bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:13:20] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/js/dataTables.select.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:13:20] "GET /arquivos_estaticos/adminlte/js/app.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:13:20] "GET /arquivos_estaticos/scripts/padrao/controle_componentes.js HTTP/1.1" 304 0
[18/Nov/2016 06:13:20] "GET /arquivos_estaticos/scripts/mask.js HTTP/1.1" 304 0
[18/Nov/2016 06:13:21] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 06:13:21] "GET /arquivos_estaticos/imagens/avatar5.png HTTP/1.1" 304 0
[18/Nov/2016 06:13:21] "GET /arquivos_estaticos/imagens/logo.png HTTP/1.1" 304 0
[18/Nov/2016 06:13:21] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 06:13:21] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 06:13:21] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2016 - 06:14:06
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
Internal Server Error: /entidade/cadastro/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 91, in cadastro_entidades
    operacao.save()
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 708, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 736, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 820, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 859, in _do_insert
    using=using, raw=raw)
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Python27\lib\site-packages\django\db\models\sql\compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\sqlite3\base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: database is locked
Internal Server Error: /entidade/cadastro/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 91, in cadastro_entidades
    operacao.save()
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 708, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 736, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 820, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 859, in _do_insert
    using=using, raw=raw)
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Python27\lib\site-packages\django\db\models\sql\compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\sqlite3\base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: database is locked
[18/Nov/2016 06:14:18] "POST /entidade/cadastro/ HTTP/1.1" 500 124542
[18/Nov/2016 06:14:35] "POST /entidade/cadastro/ HTTP/1.1" 200 33936
[18/Nov/2016 06:14:35] "GET /arquivos_estaticos/adminlte/css/AdminLTE.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:14:35] "GET /arquivos_estaticos/icones/css/font-awesome.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:14:35] "GET /arquivos_estaticos/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:14:35] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.js HTTP/1.1" 304 0
[18/Nov/2016 06:14:35] "GET /arquivos_estaticos/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:14:35] "GET /arquivos_estaticos/jquery/jquery-2.2.0.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:14:35] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.css HTTP/1.1" 304 0
[18/Nov/2016 06:14:35] "GET /arquivos_estaticos/adminlte/css/skins/skin-blue.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:14:35] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/css/dataTables.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:14:35] "GET /arquivos_estaticos/datatable/plugins/responsivo/Responsive-2.0.2/css/responsive.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:14:35] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/css/select.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:14:35] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/jquery.dataTables.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:14:35] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/js/dataTables.select.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:14:35] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/dataTables.bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:14:35] "GET /arquivos_estaticos/adminlte/js/app.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:14:35] "GET /arquivos_estaticos/scripts/padrao/controle_componentes.js HTTP/1.1" 304 0
[18/Nov/2016 06:14:35] "GET /arquivos_estaticos/scripts/mask.js HTTP/1.1" 304 0
[18/Nov/2016 06:14:35] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 06:14:35] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 06:14:35] "GET /arquivos_estaticos/imagens/avatar5.png HTTP/1.1" 304 0
[18/Nov/2016 06:14:35] "GET /arquivos_estaticos/imagens/logo.png HTTP/1.1" 304 0
[18/Nov/2016 06:14:35] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 06:14:36] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2016 - 06:15:01
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2016 - 06:15:06
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2016 - 06:15:09
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
Internal Server Error: /entidade/cadastro/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 91, in cadastro_entidades
    operacao.save()
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 708, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 736, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 820, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 859, in _do_insert
    using=using, raw=raw)
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Python27\lib\site-packages\django\db\models\sql\compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\sqlite3\base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: table entidade_operacaorestrita has no column named tipo
Internal Server Error: /entidade/cadastro/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 91, in cadastro_entidades
    operacao.save()
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 708, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 736, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 820, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 859, in _do_insert
    using=using, raw=raw)
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Python27\lib\site-packages\django\db\models\sql\compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\sqlite3\base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: table entidade_operacaorestrita has no column named tipo
[18/Nov/2016 06:16:00] "POST /entidade/cadastro/ HTTP/1.1" 500 124698
[18/Nov/2016 06:16:47] "POST /entidade/cadastro/ HTTP/1.1" 200 33936
[18/Nov/2016 06:16:47] "GET /arquivos_estaticos/adminlte/css/AdminLTE.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:16:47] "GET /arquivos_estaticos/icones/css/font-awesome.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:16:47] "GET /arquivos_estaticos/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:16:47] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.js HTTP/1.1" 304 0
[18/Nov/2016 06:16:47] "GET /arquivos_estaticos/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:16:47] "GET /arquivos_estaticos/jquery/jquery-2.2.0.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:16:48] "GET /arquivos_estaticos/adminlte/css/skins/skin-blue.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:16:48] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.css HTTP/1.1" 304 0
[18/Nov/2016 06:16:48] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/css/dataTables.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:16:48] "GET /arquivos_estaticos/datatable/plugins/responsivo/Responsive-2.0.2/css/responsive.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:16:48] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/css/select.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:16:48] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/jquery.dataTables.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:16:49] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/dataTables.bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:16:49] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/js/dataTables.select.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:16:49] "GET /arquivos_estaticos/adminlte/js/app.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:16:49] "GET /arquivos_estaticos/scripts/padrao/controle_componentes.js HTTP/1.1" 304 0
[18/Nov/2016 06:16:49] "GET /arquivos_estaticos/scripts/mask.js HTTP/1.1" 304 0
[18/Nov/2016 06:16:49] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 06:16:49] "GET /arquivos_estaticos/imagens/avatar5.png HTTP/1.1" 304 0
[18/Nov/2016 06:16:49] "GET /arquivos_estaticos/imagens/logo.png HTTP/1.1" 304 0
[18/Nov/2016 06:16:49] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 06:16:49] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 06:16:49] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2016 - 06:17:12
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
olha o cliente:  DIEGO PASTI
[18/Nov/2016 06:17:39] "POST /entidade/cadastro/ HTTP/1.1" 200 33936
[18/Nov/2016 06:17:39] "GET /arquivos_estaticos/adminlte/css/AdminLTE.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:17:39] "GET /arquivos_estaticos/icones/css/font-awesome.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:17:39] "GET /arquivos_estaticos/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:17:39] "GET /arquivos_estaticos/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:17:39] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.js HTTP/1.1" 304 0
[18/Nov/2016 06:17:39] "GET /arquivos_estaticos/jquery/jquery-2.2.0.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:17:40] "GET /arquivos_estaticos/adminlte/css/skins/skin-blue.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:17:40] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.css HTTP/1.1" 304 0
[18/Nov/2016 06:17:40] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/css/dataTables.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:17:40] "GET /arquivos_estaticos/datatable/plugins/responsivo/Responsive-2.0.2/css/responsive.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:17:40] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/css/select.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:17:40] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/jquery.dataTables.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:17:40] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/dataTables.bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:17:40] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/js/dataTables.select.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:17:40] "GET /arquivos_estaticos/adminlte/js/app.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:17:40] "GET /arquivos_estaticos/scripts/padrao/controle_componentes.js HTTP/1.1" 304 0
[18/Nov/2016 06:17:40] "GET /arquivos_estaticos/scripts/mask.js HTTP/1.1" 304 0
[18/Nov/2016 06:17:40] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 06:17:41] "GET /arquivos_estaticos/imagens/avatar5.png HTTP/1.1" 304 0
[18/Nov/2016 06:17:41] "GET /arquivos_estaticos/imagens/logo.png HTTP/1.1" 304 0
[18/Nov/2016 06:17:41] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 06:17:41] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 06:17:41] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
Performing system checks...

System check identified no issues (0 silenced).
November 18, 2016 - 06:17:54
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
olha o cliente:  DIEGO PASTI
[18/Nov/2016 06:17:59] "POST /entidade/cadastro/ HTTP/1.1" 200 33936
[18/Nov/2016 06:17:59] "GET /arquivos_estaticos/adminlte/css/AdminLTE.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:17:59] "GET /arquivos_estaticos/icones/css/font-awesome.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:17:59] "GET /arquivos_estaticos/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:17:59] "GET /arquivos_estaticos/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:17:59] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.js HTTP/1.1" 304 0
[18/Nov/2016 06:17:59] "GET /arquivos_estaticos/jquery/jquery-2.2.0.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:18:00] "GET /arquivos_estaticos/adminlte/css/skins/skin-blue.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:18:00] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.css HTTP/1.1" 304 0
[18/Nov/2016 06:18:00] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/css/dataTables.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:18:00] "GET /arquivos_estaticos/datatable/plugins/responsivo/Responsive-2.0.2/css/responsive.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:18:00] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/css/select.bootstrap.min.css HTTP/1.1" 304 0
[18/Nov/2016 06:18:00] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/jquery.dataTables.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:18:00] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/dataTables.bootstrap.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:18:00] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/js/dataTables.select.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:18:00] "GET /arquivos_estaticos/adminlte/js/app.min.js HTTP/1.1" 304 0
[18/Nov/2016 06:18:00] "GET /arquivos_estaticos/scripts/padrao/controle_componentes.js HTTP/1.1" 304 0
[18/Nov/2016 06:18:00] "GET /arquivos_estaticos/scripts/mask.js HTTP/1.1" 304 0
[18/Nov/2016 06:18:00] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 06:18:01] "GET /arquivos_estaticos/imagens/avatar5.png HTTP/1.1" 304 0
[18/Nov/2016 06:18:01] "GET /arquivos_estaticos/imagens/logo.png HTTP/1.1" 304 0
[18/Nov/2016 06:18:01] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 06:18:01] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[18/Nov/2016 06:18:01] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[18/Nov/2016 06:35:23] "POST /entidade/cadastro/ HTTP/1.1" 200 33936
Process finished with exit code 0
